### ISSUE TITLE
Provider name in example manifest

### ISSUE THREAD

**Issue by ataulm** [mitmel/SimpleContentProvider#16]
``` xml
<provider
    android:name="SampleProvider"
    android:authorities="edu.mit.mobile.android.content.example.sampleprovider"
    />
```

In the example project's manifest, the name is given as `SampleProvider`. How does this work without pre-pending the name with a period to indicate that the application package should be used?

The guidelines found on developer.android.com (http://developer.android.com/guide/topics/manifest/provider-element.html) indicate that the name attribute should be fully qualified, or the first character should be a period.
## 

In the example project, everything is under one package.
I'm asking because my application's package name is different from the package my Provider is in (the manifest is the Only place where the old package name is used, to allow updates for existing users).

The comment for the String constant in SampleProvider in the example project says:

``` java
// Each ContentProvider must have a globally unique authority. You should
// specify one here starting from your Application's package string:
```

Is it the case that it's required to start from that package string, or just that it's the practice? Under the "Designing an Authority" section on developer.android.com (http://developer.android.com/guide/topics/providers/content-provider-creating.html), it says "should" append application package name, though from the context of the paragraph, looks like it's just to avoid naming conflicts, rather than any technical reason.

**Comment by xxv** [comment]
For your first question, I think there's some fallback mechanism that adds in the "." prefix if you don't have one. I updated the example by explicitly starting it with a "." for clarity.

Re. your second question: the authority just needs to be unique and doesn't need to relate to your package at all. I've updated the comment there to clarify this.

closed by: 883a88e3aacb8e8d926b689743920c9c550df37d
