### ISSUE TITLE
Incorrect comment in the constructer for example/SampleProvider

### ISSUE THREAD

**Issue by ataulm** [mitmel/SimpleContentProvider#17]
I guess I'm nitpicking.

`example/SampleProvider.java#SampleProvider()`

``` java
// the above three statements can be repeated to create multiple data
// stores. Each will have separate tables and URIs.
```

There's only two statements above (not including the constuctor). I guess at some point there were more.

**Comment by xxv** [comment]
Thanks for nitpicking! :smile:

I've clarified documentation in that area as of 3596633095b63ac76be6037d889d183845def733.
