### ISSUE TITLE
Incomplete method comment in example project

### ISSUE THREAD

**Issue by ataulm** [mitmel/SimpleContentProvider#18]
``` java
// this is called when the activity is re-started by the system with a new intent. This is only
// really used with the
```

In `SimpleContentProviderExample#onNewIntent(Intent)` the method comment is incomplete. I haven't felt this way since finishing Harry Potter 6.

**Comment by xxv** [comment]
Fixed in b1e704b6c78b4d3eda38e3d3a6017a65cbd58068.
